In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import sys
sys.path.append('../..')
from src.svm.full import classify

In [4]:
import numpy as np
import numpy.random as npr

In [5]:
n = 150

class1 = npr.rand(n // 3, 2)
class2 = npr.rand(n // 3, 2)
class3 = npr.rand(n // 3, 2)

In [6]:
theta = np.pi / 6.0
r = np.cos(theta)
s = np.sin(theta)
rotation = np.array([[r, s], [s, -r]])

In [7]:
rotation

array([[ 0.8660254,  0.5      ],
       [ 0.5      , -0.8660254]])

In [8]:
class1

array([[0.98392882, 0.10742102],
       [0.79519841, 0.56792591],
       [0.22506211, 0.38844626],
       [0.26295341, 0.58842283],
       [0.32807428, 0.43989351],
       [0.73967186, 0.93574853],
       [0.14016165, 0.95850778],
       [0.47741305, 0.83076671],
       [0.2601496 , 0.0380189 ],
       [0.61947585, 0.60339993],
       [0.16921792, 0.17541285],
       [0.75771072, 0.0613912 ],
       [0.86402358, 0.33172476],
       [0.75797859, 0.17689091],
       [0.043905  , 0.01922083],
       [0.87872488, 0.93813584],
       [0.40996669, 0.97926351],
       [0.84010452, 0.06117073],
       [0.42857293, 0.33294416],
       [0.49773748, 0.62444468],
       [0.70079859, 0.80542115],
       [0.93438479, 0.79557397],
       [0.82639415, 0.85380026],
       [0.8338684 , 0.63927401],
       [0.09082932, 0.21363652],
       [0.56891164, 0.70113757],
       [0.8223796 , 0.53641434],
       [0.00271663, 0.46974751],
       [0.75503316, 0.26221466],
       [0.67349796, 0.70505542],
       [0.

In [9]:
samples = np.dot(np.vstack([class1, class2, class3]), rotation)

In [10]:
samples

array([[ 9.05817862e-01,  3.98935073e-01],
       [ 9.72624974e-01, -9.42390613e-02],
       [ 3.89132639e-01, -2.23873276e-01],
       [ 5.21935745e-01, -3.78112414e-01],
       [ 5.04067417e-01, -2.16921810e-01],
       [ 1.10844888e+00, -4.40546073e-01],
       [ 6.00637436e-01, -7.60011262e-01],
       [ 8.28835187e-01, -4.80758552e-01],
       [ 2.44305610e-01,  9.71494670e-02],
       [ 8.38181789e-01, -2.12821746e-01],
       [ 2.34253441e-01, -6.73030272e-02],
       [ 6.86892329e-01,  3.25689023e-01],
       [ 9.14128749e-01,  1.44729724e-01],
       [ 7.44874173e-01,  2.25797272e-01],
       [ 4.76332611e-02,  5.30677633e-03],
       [ 1.23006599e+00, -3.73087033e-01],
       [ 8.44673318e-01, -6.43083731e-01],
       [ 7.58137219e-01,  3.67076857e-01],
       [ 5.37627126e-01, -7.40516398e-02],
       [ 7.43275644e-01, -2.91916218e-01],
       [ 1.00961996e+00, -3.47115884e-01],
       [ 1.20698795e+00, -2.21794871e-01],
       [ 1.14257845e+00, -3.26215645e-01],
       [ 1.

In [20]:
labels = np.zeros(n)

third = n // 3

labels[:third] = 0
labels[60:80] = 1
labels[100:] = 2

In [21]:
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [22]:
p, q, g, h, x = classify(samples, labels)

     pcost       dcost       gap    pres   dres
 0:  4.9865e-01  1.8209e+02  3e+02  2e+00  2e+02
 1:  1.0653e+00  3.9089e+02  9e+01  1e+00  8e+01
 2:  1.0753e+00  4.3086e+04  9e+01  1e+00  8e+01
 3:  1.0754e+00  4.2700e+08  5e+02  1e+00  8e+01
 4:  1.0754e+00  4.2273e+14  4e+06  1e+00  8e+01
 5:  1.0754e+00  4.1850e+22  4e+12  1e+00  8e+01
 6:  1.0754e+00  4.1432e+32  4e+20  1e+00  8e+01
 7:  1.0754e+00  4.1015e+44  4e+30  1e+00  8e+01
 8:  1.0754e+00  4.0695e+58  4e+42  1e+00  8e+01
 9:  1.0754e+00  3.4181e+74  3e+56  1e+00  8e+01
10:  7.0825e+01  6.8495e+104  7e+86  1e+00  8e+01
11:  1.9259e+02  1.3429e+106  1e+88  1e+00  8e+01
12:  4.8711e+02  4.6115e+106  5e+88  1e+00  8e+01
13:  1.5876e+03  1.6508e+107  2e+89  1e+00  8e+01
14:  1.5260e+03  1.6508e+143  2e+125  7e-01  2e-14
15:  1.6368e+01  1.6335e+179  2e+161  7e-01  4e-16
16:  1.2685e+00  1.5487e+215  2e+197  7e-01  3e-16
17:  1.5938e+00  1.5487e+215  2e+197  7e-01  2e-16
18:  4.4032e+00  1.5487e+215  2e+197  7e-01  2e-16
19:  8.

In [23]:
x

<3x1 matrix, tc='d'>

In [24]:
str(x)

'[ 5.51e-01]\n[-2.00e-01]\n[ 2.03e+62]\n'